### ISSUE TITLE
Support Glance beta01 API breaking changes

### ISSUE THREAD

**Issue by vetoketju** [google/glance-experimental-tools#10]
## Describe the bug
AppWidgetConfigurationScaffold crashes with androidx.glance:glance-*:1.0.0-beta01. Content() function of GlanceAppWidget got deprecated and AppWidgetConfigurationScaffold is trying to call that function. 

"Updated GlanceAppWidget to use provideGlance as the main entrypoint. GlanceAppWidget.Content is now deprecated. "

## Environment:
- androidx.glance:glance-*:1.0.0-beta01
- Glance Experimental Tools version: 0.2.2

**Comment by miduch** [comment]
any update on this?

**Comment by marcelpinto** [comment]
Thanks for the ping. I am not able to provide a timeline on when we can update the experimental tools for now but PRs are welcome :)
