### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method Content

### ISSUE THREAD

**Issue by aabadaa** [google/glance-experimental-tools#21]
The exception is being thowed here:

@ExperimentalGlanceRemoteViewsApi
private suspend fun GlanceAppWidget.compose(
    context: Context,
    size: DpSize,
    state: Any?
): RemoteViews = glanceRemoteViews.compose(
    context = context,
    size = size,
    state = state,
    content = { Content() }
).remoteViews

here is my widget:
object NoteWidget : GlanceAppWidget() {

    override val stateDefinition: GlanceStateDefinition<*> = PreferencesGlanceStateDefinition
    override suspend fun provideGlance(context: Context, id: GlanceId) {
        provideContent {
            GlanceTheme(colors =MyAppWidgetGlanceColorScheme.colors) { /* a normal content */ } 
    }
}

the exception appears as soon as the user try to add a widget and the configuration activity is launched

## Environment:
 - Android OS version: 14
 - Device:Resizable expermental api 34
 - Glance Experimental Tools version: 0.2.2

**Comment by JamieYee** [comment]
You can’t just directly implement appwidget-configuration and appwidget-viewer and copy them into your own project to make them work.
